
/**************************************************************
 *	
 *	Ding, 8 bit, 11025Hz,
 *	1 channel, 10250 bytes/channel
 *	Total Size: 1 * 10250 + 4 (header) = 10294 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\madel\OneDrive\Documents\_School\CS2261\Project\M4\Ding.wav
 *	Time-stamp: Thu Nov 29 21:23:44 2018
 *	
 **************************************************************/

#ifndef __DINGH__
#define __DINGH__

#define DINGFREQ 11025
#define DINGLEN 10250

extern const unsigned char Ding[10250];

#endif /* __DINGH__ */
