
/**************************************************************
 *	
 *	GameSong, 8 bit, 11025Hz,
 *	1 channel, 2977920 bytes/channel
 *	Total Size: 1 * 2977920 + 4 (header) = 2977964 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\madel\OneDrive\Documents\_School\CS2261\Project\M4\GameSong.wav
 *	Time-stamp: Mon Nov 26 02:07:11 2018
 *	
 **************************************************************/

#ifndef __GAMESONGH__
#define __GAMESONGH__

#define GAMESONGFREQ 11025
#define GAMESONGLEN 2977920

extern const unsigned char GameSong[2977920];

#endif /* __GAMESONGH__ */
