
/**************************************************************
 *	
 *	JumpAround, 8 bit, 11025Hz,
 *	1 channel, 2371392 bytes/channel
 *	Total Size: 1 * 2371392 + 4 (header) = 2371436 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\madel\OneDrive\Documents\_School\CS2261\Project\M4\JumpAround.wav
 *	Time-stamp: Sun Nov 25 15:17:29 2018
 *	
 **************************************************************/

#ifndef __JUMPAROUNDH__
#define __JUMPAROUNDH__

#define JUMPAROUNDFREQ 11025
#define JUMPAROUNDLEN 2371392

extern const unsigned char JumpAround[2371392];

#endif /* __JUMPAROUNDH__ */
