
/**************************************************************
 *	
 *	Lose, 8 bit, 11025Hz,
 *	1 channel, 49370 bytes/channel
 *	Total Size: 1 * 49370 + 4 (header) = 49414 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\madel\OneDrive\Documents\_School\CS2261\go-go-googles-gba\Lose.wav
 *	Time-stamp: Tue Dec 04 23:09:37 2018
 *	
 **************************************************************/

#ifndef __LOSEH__
#define __LOSEH__

#define LOSEFREQ 11025
#define LOSELEN 49370

extern const unsigned char Lose[49370];

#endif /* __LOSEH__ */
