
/**************************************************************
 *	
 *	Pause, 8 bit, 11025Hz,
 *	1 channel, 3137 bytes/channel
 *	Total Size: 1 * 3137 + 4 (header) = 3181 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\madel\OneDrive\Documents\_School\CS2261\go-go-googles-gba\Pause.wav
 *	Time-stamp: Tue Dec 04 23:26:34 2018
 *	
 **************************************************************/

#ifndef __PAUSEH__
#define __PAUSEH__

#define PAUSEFREQ 11025
#define PAUSELEN 3137

extern const unsigned char Pause[3137];

#endif /* __PAUSEH__ */
