
/**************************************************************
 *	
 *	Splat, 8 bit, 11025Hz,
 *	1 channel, 1438 bytes/channel
 *	Total Size: 1 * 1438 + 4 (header) = 1482 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\madel\OneDrive\Documents\_School\CS2261\go-go-googles-gba\Splat.wav
 *	Time-stamp: Tue Dec 04 23:04:06 2018
 *	
 **************************************************************/

#ifndef __SPLATH__
#define __SPLATH__

#define SPLATFREQ 11025
#define SPLATLEN 1438

extern const unsigned char Splat[1438];

#endif /* __SPLATH__ */
