
/**************************************************************
 *	
 *	Unpause, 8 bit, 11025Hz,
 *	1 channel, 2745 bytes/channel
 *	Total Size: 1 * 2745 + 4 (header) = 2789 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\madel\OneDrive\Documents\_School\CS2261\go-go-googles-gba\Unpause.wav
 *	Time-stamp: Tue Dec 04 23:26:12 2018
 *	
 **************************************************************/

#ifndef __UNPAUSEH__
#define __UNPAUSEH__

#define UNPAUSEFREQ 11025
#define UNPAUSELEN 2745

extern const unsigned char Unpause[2745];

#endif /* __UNPAUSEH__ */
