
/**************************************************************
 *	
 *	Win, 8 bit, 11025Hz,
 *	1 channel, 100959 bytes/channel
 *	Total Size: 1 * 100959 + 4 (header) = 101003 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\madel\OneDrive\Documents\_School\CS2261\go-go-googles-gba\Win.wav
 *	Time-stamp: Tue Dec 04 23:16:22 2018
 *	
 **************************************************************/

#ifndef __WINH__
#define __WINH__

#define WINFREQ 11025
#define WINLEN 100959

extern const unsigned char Win[100959];

#endif /* __WINH__ */
